/**
 * Каталог предметов сезона — названия и описания в лоре Minecraft.
 * Slug'и стабильны для БД.
 */
import type { CatalogItemSeed, CatalogRecipeSeed } from "./item-catalog-types";

export const MC_MATERIALS: CatalogItemSeed[] = [
  {
    slug: "iron_shard",
    name: "Обломок железной руды",
    description: "Выпадает из слота наград. Переплавляется на верстаке в полезные вещи.",
    rarity: "COMMON",
    kind: "MATERIAL",
    effectsJson: {},
  },
  {
    slug: "gold_dust",
    name: "Пыль золотого слитка",
    description: "Блестит, как самородок в глубокой шахте. Нужна для редких рецептов.",
    rarity: "UNCOMMON",
    kind: "MATERIAL",
    effectsJson: {},
  },
  {
    slug: "emerald_splinter",
    name: "Осколок изумрудной жилы",
    description: "Жители деревни оценили бы по достоинству. Ключ к легендарным крафтам.",
    rarity: "RARE",
    kind: "MATERIAL",
    effectsJson: {},
  },
  {
    slug: "streamer_tear",
    name: "Капля слезы гаста",
    description: "Горькая, как неудачный дроп. Редкий катализатор на верстаке.",
    rarity: "UNCOMMON",
    kind: "MATERIAL",
    effectsJson: {},
  },
  {
    slug: "junk_scrap",
    name: "Ржавый металлолом",
    description: "Пять штук можно переплавить на верстаке во что-то годное.",
    rarity: "COMMON",
    kind: "MATERIAL",
    effectsJson: {},
  },
];

export const MC_MODIFIER_ITEMS: CatalogItemSeed[] = [
  {
    slug: "good_flat_4",
    name: "Лесное яблоко",
    description: "Съел перед забегом — +4 очка за прохождение.",
    rarity: "COMMON",
    kind: "MODIFIER",
    effectsJson: { flatScoreBonus: 4 },
  },
  {
    slug: "good_flat_8",
    name: "Сияющее золотое яблоко",
    description: "Согревает желудок и дух — +8 очков за прохождение.",
    rarity: "UNCOMMON",
    kind: "MODIFIER",
    effectsJson: { flatScoreBonus: 8 },
  },
  {
    slug: "bad_flat_3",
    name: "Гнилостная плоть",
    description: "Пахнет подземельем — −3 очка за прохождение.",
    rarity: "COMMON",
    kind: "MODIFIER",
    effectsJson: { flatScorePenalty: 3 },
  },
  {
    slug: "bad_flat_6",
    name: "Тухлый картофель",
    description: "Съел по ошибке — −6 очков за прохождение.",
    rarity: "UNCOMMON",
    kind: "MODIFIER",
    effectsJson: { flatScorePenalty: 6 },
  },
  {
    slug: "anabolics",
    name: "Зелье огнестойкости",
    description: "Выпей — игра выпадет на самом мягком уровне сложности.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { difficultyEasyBias: true, difficultyRerolls: 2 },
  },
  {
    slug: "one_of_oneils",
    name: "Клинок из незерита",
    description: "Тяжёлый и жестокий — максимальная сложность забега.",
    rarity: "EPIC",
    kind: "MODIFIER",
    effectsJson: { difficultyHardBias: true, difficultyRerolls: 2 },
  },
  {
    slug: "parachute",
    name: "Перо медленного падения",
    description: "При дропе штраф вдвое мягче — мягкая посадка в блоки.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { dropPenaltyMultiplier: 0.5 },
  },
  {
    slug: "wasted",
    name: "Заряд файерверка",
    description: "Взрывной дроп — штраф как за полное прохождение.",
    rarity: "EPIC",
    kind: "MODIFIER",
    effectsJson: { wastedDrop: true },
  },
  {
    slug: "asnaeb",
    name: "Тотем бессмертия",
    description: "Древняя защита — −50% к штрафу при дропе.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { penaltyReduction: 0.5 },
  },
  {
    slug: "body_armor",
    name: "Незеритовый нагрудник",
    description: "Крепкая броня — вор не сунется в инвентарь.",
    rarity: "UNCOMMON",
    kind: "MODIFIER",
    effectsJson: { blockRatSteal: true },
  },
  {
    slug: "small_theft_effect",
    name: "Кость сталкера",
    description: "После победы шанс стащить материал у лидера таблицы.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { ratSteal: true },
  },
  {
    slug: "snatched",
    name: "Кирка с шелковым касанием",
    description: "+3 очка и кража материала у лидера после игры.",
    rarity: "EPIC",
    kind: "MODIFIER",
    effectsJson: { flatScoreBonus: 3, ratSteal: true },
  },
  {
    slug: "factory_assembly",
    name: "Стол плотника",
    description: "Очки только от HLTB — скорость прохождения не даёт бонуса.",
    rarity: "EPIC",
    kind: "MODIFIER",
    effectsJson: { factoryAssembly: true },
  },
  {
    slug: "speedometer",
    name: "Redstone-часы",
    description: "−10 очков, если прошли на 2+ часа быстрее HLTB.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { speedrunTaxHours: 2, speedrunTaxPenalty: 10 },
  },
  {
    slug: "number_9_extra",
    name: "Пузырёк опыта",
    description: "+25% очков за прохождение.",
    rarity: "EPIC",
    kind: "MODIFIER",
    effectsJson: { scoreMult: 1.25 },
  },
  {
    slug: "reroll_fetishist",
    name: "Компас путника",
    description: "Переброс сложности и небольшой бонус очков для стримеров внизу таблицы.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { difficultyRerolls: 1, underdogScoreBonus: 0.05, flatScoreBonus: 4 },
  },
  {
    slug: "city_map",
    name: "Покорёженная карта",
    description: "Гайды разрешены: −10% очков, но −35% штрафа при дропе.",
    rarity: "UNCOMMON",
    kind: "MODIFIER",
    effectsJson: { scoreMult: 0.9, penaltyReduction: 0.35 },
  },
  {
    slug: "container_with_junk",
    name: "Аудиокнига Ozon",
    description:
      "Челлендж: обязательно проходить игру под аудиокнигу Ozon. Даёт +2 спина без штрафа по очкам.",
    rarity: "UNCOMMON",
    kind: "MODIFIER",
    effectsJson: { audiobookChallenge: true, extraLootRolls: 2 },
  },
  {
    slug: "genre_expert",
    name: "Жанровый эксперт",
    description: "Перед завершением аукциона можно выбрать жанр игры вручную.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { genreExpertChoice: true, flatScoreBonus: 6 },
  },
  {
    slug: "genre_fever",
    name: "Жанровая лихорадка",
    description: "Дебафф: следующий аукцион только жанры action/adventure и −6 очков.",
    rarity: "EPIC",
    kind: "MODIFIER",
    effectsJson: { auctionForcedGenres: ["action", "adventure"], flatScorePenalty: 6 },
  },
  {
    slug: "old_timer_lawlessness",
    name: "Пластинка «13»",
    description: "Для длинных игр (25+ ч): +12% очков и +1 спин слота наград.",
    rarity: "EPIC",
    kind: "MODIFIER",
    effectsJson: { longGameHltbMin: 25, longGameScoreBonus: 0.12, longGameLootBonus: 1 },
  },
  {
    slug: "shorties_epidemic",
    name: "Сноп сена",
    description: "Игры до 8 ч HLTB: +10 очков и +1 спин слота наград.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { shortGameHltbMax: 8, shortGameFlatBonus: 10, shortGameLootBonus: 1 },
  },
  {
    slug: "free_spins",
    name: "Звёздный осколок Незера",
    description: "+2 доп. спина в слоте наград после игры.",
    rarity: "LEGENDARY",
    kind: "MODIFIER",
    effectsJson: { extraLootRolls: 2, pinataLootBonus: 1 },
  },
  {
    slug: "leprechaun_boost",
    name: "Золотая морковь",
    description: "Выше шанс редкого лута в слоте; +2 очка.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { rareDropMult: 1.4, flatScoreBonus: 2 },
  },
  {
    slug: "leprechaun_debuff",
    name: "Дурманный корень",
    description: "−5% очков, зато +2 спина в слоте наград.",
    rarity: "UNCOMMON",
    kind: "MODIFIER",
    effectsJson: { scoreMult: 0.95, extraLootRolls: 2 },
  },
  {
    slug: "bowling_bro",
    name: "Ком снега",
    description: "+5% очков и +1 спин слота наград.",
    rarity: "UNCOMMON",
    kind: "MODIFIER",
    effectsJson: { scoreMult: 1.05, extraLootRolls: 1 },
  },
  {
    slug: "movie_ticket",
    name: "Блокнот путешественника",
    description: "Для коротких игр (до 10 ч): +15 очков и +1 спин слота наград.",
    rarity: "RARE",
    kind: "MODIFIER",
    effectsJson: { shortGameHltbMax: 10, shortGameFlatBonus: 15, shortGameLootBonus: 1 },
  },
];

export const MC_RECIPES: CatalogRecipeSeed[] = [
  {
    slug: "anabolics_recipe",
    name: "Зелье огнестойкости",
    resultSlug: "anabolics",
    ingredients: [
      { slug: "iron_shard", quantity: 3 },
      { slug: "streamer_tear", quantity: 1 },
    ],
  },
  {
    slug: "parachute_recipe",
    name: "Перо медленного падения",
    resultSlug: "parachute",
    ingredients: [
      { slug: "iron_shard", quantity: 2 },
      { slug: "gold_dust", quantity: 2 },
    ],
  },
  {
    slug: "city_map_recipe",
    name: "Покорёженная карта",
    resultSlug: "city_map",
    ingredients: [
      { slug: "iron_shard", quantity: 2 },
      { slug: "gold_dust", quantity: 1 },
    ],
  },
  {
    slug: "junk_recycle_recipe",
    name: "Переплавка лома",
    resultSlug: "bad_flat_3",
    ingredients: [{ slug: "junk_scrap", quantity: 5 }],
  },
  {
    slug: "reroll_fetishist_recipe",
    name: "Компас путника",
    resultSlug: "reroll_fetishist",
    ingredients: [
      { slug: "gold_dust", quantity: 2 },
      { slug: "emerald_splinter", quantity: 1 },
    ],
  },
  {
    slug: "free_spins_recipe",
    name: "Звёздный осколок Незера",
    resultSlug: "free_spins",
    ingredients: [
      { slug: "emerald_splinter", quantity: 2 },
      { slug: "streamer_tear", quantity: 3 },
      { slug: "gold_dust", quantity: 2 },
    ],
  },
];
