import type { SoundDefinition, SoundId } from "./types";

export const SOUND_REGISTRY: Record<SoundId, SoundDefinition> = {
  "ui.hover": {
    id: "ui.hover",
    path: "/audio/ui/hover.ogg",
    category: "ui",
    volume: 0.25,
    fallback: "uiClickLight",
  },
  "ui.click": {
    id: "ui.click",
    path: "/audio/ui/click.ogg",
    category: "ui",
    volume: 0.35,
    fallback: "uiClickConfirm",
  },
  "ui.pageOpen": {
    id: "ui.pageOpen",
    path: "/audio/ui/page-open.ogg",
    category: "ui",
    volume: 0.3,
    fallback: "pageOpen",
  },
  "resource.wood": {
    id: "resource.wood",
    path: "/audio/resources/wood.ogg",
    category: "resources",
    volume: 0.4,
    fallback: "resourceWood",
  },
  "resource.stone": {
    id: "resource.stone",
    path: "/audio/resources/stone.ogg",
    category: "resources",
    volume: 0.4,
    fallback: "resourceStone",
  },
  "resource.iron": {
    id: "resource.iron",
    path: "/audio/resources/iron.ogg",
    category: "resources",
    volume: 0.4,
    fallback: "resourceIron",
  },
  "resource.gold": {
    id: "resource.gold",
    path: "/audio/resources/gold.ogg",
    category: "resources",
    volume: 0.45,
    fallback: "resourceGold",
  },
  "resource.diamond": {
    id: "resource.diamond",
    path: "/audio/resources/diamond.ogg",
    category: "resources",
    volume: 0.5,
    fallback: "resourceDiamond",
  },
  "resource.emerald": {
    id: "resource.emerald",
    path: "/audio/resources/emerald.ogg",
    category: "resources",
    volume: 0.5,
    fallback: "resourceEmerald",
  },
  "player.levelUp": {
    id: "player.levelUp",
    path: "/audio/ui/level-up.ogg",
    category: "ui",
    volume: 0.55,
    fallback: "levelUp",
  },
  "achievement.unlock": {
    id: "achievement.unlock",
    path: "/audio/achievements/unlock.ogg",
    category: "achievements",
    volume: 0.6,
    fallback: "achievementUnlock",
  },
  "achievement.secretUnlock": {
    id: "achievement.secretUnlock",
    path: "/audio/achievements/secret.ogg",
    category: "achievements",
    volume: 0.65,
    fallback: "achievementUnlock",
  },
  "artifact.epic": {
    id: "artifact.epic",
    path: "/audio/artifacts/epic.ogg",
    category: "artifacts",
    volume: 0.7,
    fallback: "artifactEpic",
  },
  "craft.bench": {
    id: "craft.bench",
    path: "/audio/ui/craft.ogg",
    category: "ui",
    volume: 0.45,
    fallback: "craftBench",
  },
  "chest.open": {
    id: "chest.open",
    path: "/audio/ui/chest-open.ogg",
    category: "ui",
    volume: 0.5,
    fallback: "chestOpen",
  },
  "boss.victory": {
    id: "boss.victory",
    path: "/audio/bosses/victory.ogg",
    category: "bosses",
    volume: 0.75,
    fallback: "bossVictory",
  },
  "boss.attack": {
    id: "boss.attack",
    path: "/audio/bosses/attack.ogg",
    category: "bosses",
    volume: 0.4,
    fallback: "resourceIron",
  },
  "drop.legendary": {
    id: "drop.legendary",
    path: "/audio/ui/legendary.ogg",
    category: "artifacts",
    volume: 0.7,
    fallback: "legendaryDrop",
  },
  "easter.creeperExplosion": {
    id: "easter.creeperExplosion",
    path: "/audio/eastereggs/explosion.ogg",
    category: "eastereggs",
    volume: 0.65,
    fallback: "creeperExplosion",
  },
  "easter.creeperHiss": {
    id: "easter.creeperHiss",
    path: "/audio/eastereggs/creeper-hiss.ogg",
    category: "eastereggs",
    volume: 0.5,
    fallback: "creeperHiss",
  },
  "easter.herobrine": {
    id: "easter.herobrine",
    path: "/audio/eastereggs/herobrine.ogg",
    category: "eastereggs",
    volume: 0.45,
    fallback: "herobrineCreepy",
  },
  "easter.enderman": {
    id: "easter.enderman",
    path: "/audio/eastereggs/enderman.ogg",
    category: "eastereggs",
    volume: 0.4,
    fallback: "endermanTeleport",
  },
  "easter.secretPage": {
    id: "easter.secretPage",
    path: "/audio/eastereggs/secret-page.ogg",
    category: "eastereggs",
    volume: 0.5,
    fallback: "secretPageAncient",
  },
  "ambient.wind": {
    id: "ambient.wind",
    path: "/audio/ambient/wind.ogg",
    category: "ambient",
    volume: 0.2,
    fallback: "ambientWind",
  },
  "ambient.cave": {
    id: "ambient.cave",
    path: "/audio/ambient/cave.ogg",
    category: "ambient",
    volume: 0.18,
    fallback: "ambientCave",
  },
  "ambient.footsteps": {
    id: "ambient.footsteps",
    path: "/audio/ambient/footsteps.ogg",
    category: "ambient",
    volume: 0.15,
    fallback: "ambientFootsteps",
  },
  "ambient.torch": {
    id: "ambient.torch",
    path: "/audio/ambient/torch.ogg",
    category: "ambient",
    volume: 0.12,
    fallback: "ambientTorch",
  },
  "ambient.water": {
    id: "ambient.water",
    path: "/audio/ambient/water.ogg",
    category: "ambient",
    volume: 0.14,
    fallback: "ambientWater",
  },
  "ambient.woodCreak": {
    id: "ambient.woodCreak",
    path: "/audio/ambient/wood-creak.ogg",
    category: "ambient",
    volume: 0.14,
    fallback: "ambientWoodCreak",
  },
  "ambient.night.cave": {
    id: "ambient.night.cave",
    path: "/audio/ambient/night-cave.ogg",
    category: "ambient",
    volume: 0.12,
    fallback: "ambientNightCave",
  },
  "ambient.night.footsteps": {
    id: "ambient.night.footsteps",
    path: "/audio/ambient/night-footsteps.ogg",
    category: "ambient",
    volume: 0.1,
    fallback: "ambientNightFootsteps",
  },
  "ambient.night.enderman": {
    id: "ambient.night.enderman",
    path: "/audio/ambient/night-enderman.ogg",
    category: "ambient",
    volume: 0.1,
    fallback: "ambientNightEnderman",
  },
  "ambient.season.forest": {
    id: "ambient.season.forest",
    path: "/audio/ambient/season-forest.ogg",
    category: "ambient",
    volume: 0.12,
    fallback: "ambientForest",
    loop: true,
  },
  "ambient.season.desert": {
    id: "ambient.season.desert",
    path: "/audio/ambient/season-desert.ogg",
    category: "ambient",
    volume: 0.12,
    fallback: "ambientDesert",
    loop: true,
  },
  "ambient.season.snow": {
    id: "ambient.season.snow",
    path: "/audio/ambient/season-snow.ogg",
    category: "ambient",
    volume: 0.1,
    fallback: "ambientSnow",
    loop: true,
  },
  "ambient.season.nether": {
    id: "ambient.season.nether",
    path: "/audio/ambient/season-nether.ogg",
    category: "ambient",
    volume: 0.14,
    fallback: "ambientNether",
    loop: true,
  },
  "ambient.season.end": {
    id: "ambient.season.end",
    path: "/audio/ambient/season-end.ogg",
    category: "ambient",
    volume: 0.1,
    fallback: "ambientEnd",
    loop: true,
  },
  "arcade.slotTick": {
    id: "arcade.slotTick",
    path: "/audio/arcade/reel-tick.ogg",
    category: "ui",
    volume: 0.26,
    fallback: "slotTick",
  },
  "arcade.slotStop": {
    id: "arcade.slotStop",
    path: "/audio/arcade/reel-stop.ogg",
    category: "ui",
    volume: 0.42,
    fallback: "slotReelStop",
  },
  "arcade.slotLand": {
    id: "arcade.slotLand",
    path: "/audio/arcade/slot-land.ogg",
    category: "ui",
    volume: 0.34,
    fallback: "slotLand",
  },
  "arcade.slotRotten": {
    id: "arcade.slotRotten",
    path: "/audio/arcade/rotten-boom.ogg",
    category: "ui",
    volume: 0.62,
    fallback: "creeperExplosion",
  },
  "arcade.slotWin": {
    id: "arcade.slotWin",
    path: "/audio/arcade/slot-win.ogg",
    category: "ui",
    volume: 0.5,
    fallback: "slotWin",
  },
};

export const RANDOM_AMBIENT_SOUNDS: SoundId[] = [
  "ambient.wind",
  "ambient.cave",
  "ambient.footsteps",
  "ambient.torch",
  "ambient.water",
  "ambient.woodCreak",
];

export const NIGHT_AMBIENT_SOUNDS: SoundId[] = [
  "ambient.night.cave",
  "ambient.night.footsteps",
  "ambient.night.enderman",
];

export function getSoundDefinition(id: SoundId): SoundDefinition {
  return SOUND_REGISTRY[id];
}
